version: '3'
services:
  pg:
    image: postgres:16.2
    volumes:
      - proxy_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: abc123test
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

  grafana:
    image: grafana/grafana
    volumes:
      - grafana_storage:/var/lib/grafana
    ports:
      - 3000:3000

  influxdb:
    image: influxdb:2
    volumes:
      - influxdb2_data:/var/lib/influxdb2
      - influxdb2_config:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: abc123test
      DOCKER_INFLUXDB_INIT_ORG: me@ruben.io
      DOCKER_INFLUXDB_INIT_BUCKET: init_bucket
    ports:
      - 8086:8086

volumes:
  proxy_db:
  grafana_storage:
  influxdb2_data:
  influxdb2_config: