version: '3'
services:
  pg:
    image: postgres:16.2
    volumes:
      - proxy_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: abc123test
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
volumes:
  proxy_db: